/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d7",
        "secondary": "#9d4300",
        "outline": "#737686",
        "surface-container-low": "#f2f3ff",
        "surface": "#faf8ff",
        "secondary-fixed": "#ffdbca",
        "error-container": "#ffdad6",
        "tertiary": "#006058",
        "secondary-container": "#fd761a",
        "on-surface-variant": "#434655",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "surface-tint": "#0053db",
        "on-tertiary-container": "#b3fff3",
        "on-surface": "#131b2e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#89f5e7",
        "surface-container-highest": "#dae2fd",
        "primary-container": "#2563eb",
        "on-secondary-container": "#5c2400",
        "tertiary-container": "#007b71",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-tertiary-fixed-variant": "#005049",
        "secondary-fixed-dim": "#ffb690",
        "primary": "#004ac6",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed": "#341100",
        "background": "#faf8ff",
        "on-primary-container": "#eeefff",
        "inverse-on-surface": "#eef0ff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#6bd8cb",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed-variant": "#783200",
        "surface-variant": "#dae2fd",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#eaedff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#00174b",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed": "#00201d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xl": "80px",
        "lg": "48px",
        "md": "24px",
        "margin-desktop": "64px",
        "xs": "4px",
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
}
